# Generated by Django 4.2.3 on 2024-04-08 04:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumWedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images', verbose_name='Ảnh nhỏ (hiển thị ở ngoài trang chủ)')),
                ('image_large', models.FileField(blank=True, null=True, unique=True, upload_to='static/images', verbose_name='Ảnh lớn (hiển thị trong slide)')),
                ('type', models.IntegerField(choices=[(1, 'Ảnh 1'), (2, 'Ảnh 2'), (3, 'Ảnh 3'), (4, 'Ảnh 4'), (5, 'Ảnh 5'), (6, 'Ảnh 6'), (7, 'Ảnh 7'), (8, 'Ảnh 8'), (9, 'Ảnh 9'), (10, 'Ảnh 10'), (11, 'Ảnh 11')], unique=True, verbose_name='Vị trí ảnh')),
            ],
            options={
                'verbose_name': 'Album ảnh tiệc cưới',
                'verbose_name_plural': 'Album ảnh tiệc cưới',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images', verbose_name='Banner hiển thị ở trang chủ')),
                ('location', models.IntegerField(choices=[(1, 'Vị trí 1'), (2, 'Vị trí 2'), (3, 'Vị trí 3'), (4, 'Vị trí 4')], unique=True, verbose_name='Vị trí')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Câu chuyện tình yêu',
                'verbose_name_plural': 'Câu chuyện tình yêu',
            },
        ),
        migrations.CreateModel(
            name='WeddingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='tiêu đề (vd: Lễ ăn hỏi, tiệc cưới nhà trai/gái,...)')),
                ('date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Thời gian tổ chức sự kiện')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ')),
                ('map', models.TextField(blank=True, null=True, verbose_name='Liên kết bản đồ (google map)')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Ưu tiên')),
            ],
            options={
                'verbose_name': 'Sự kiện tiệc cưới',
                'verbose_name_plural': 'Sự kiện tiệc cưới',
            },
        ),
        migrations.CreateModel(
            name='WendingPersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên (cô dâu hoặc chú rể)')),
                ('dad', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bố')),
                ('mother', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mẹ')),
                ('contetnt', models.TextField(verbose_name='Giới thiệu (cô dâu hoặc chú rể)')),
                ('link', models.TextField(verbose_name='Link liên kết (vd: facebook)')),
            ],
            options={
                'verbose_name': 'Nhân vật cưới',
                'verbose_name_plural': 'Nhân vật cưới',
            },
        ),
    ]
