# Generated by Django 4.2.3 on 2024-04-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
