# Generated by Django 4.2.3 on 2024-04-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
