# Generated by Django 4.2.3 on 2024-04-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_alter_story_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='WendingPersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images')),
                ('dad', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bố')),
                ('mother', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mẹ')),
                ('contetnt', models.TextField(verbose_name='Giới thiệu (cô dâu hoặc chú rể)')),
                ('link', models.TextField(verbose_name='Link liên kết (vd: facebook)')),
            ],
        ),
    ]
