# Generated by Django 4.2.3 on 2024-04-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_alter_banner_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestbookNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sổ lưu bút',
                'verbose_name_plural': 'Sổ lưu bút',
            },
        ),
    ]
