# Generated by Django 4.2.3 on 2024-04-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_wendingpersion'),
    ]

    operations = [
        migrations.AddField(
            model_name='wendingpersion',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên (cô dâu hoặc chú rể)'),
        ),
    ]
