# Generated by Django 4.2.3 on 2024-04-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_rename_full_name_guestbooknumber_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề (vd: Mừng cưới chú rể/cô dâu,...)')),
                ('image', models.FileField(unique=True, upload_to='static/images', verbose_name='Ảnh mã QR')),
                ('bank', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên ngân hàng')),
                ('account', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên ngân hàng')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số tài khoản')),
                ('branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên chi nhánh')),
            ],
            options={
                'verbose_name': 'Hộp mừng cưới',
                'verbose_name_plural': 'Hộp mừng cưới',
            },
        ),
    ]
