# Generated by Django 4.2.3 on 2024-04-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_wendingpersion_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='tiêu đề (vd: Lễ ăn hỏi, tiệc cưới nhà trai/gái,...)')),
                ('date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Thời gian tổ chức sự kiện')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ')),
                ('map', models.TextField(blank=True, null=True, verbose_name='Liên kết bản đồ (google map)')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Ưu tiên')),
            ],
        ),
    ]
